version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-
      - run:
          name: Install python
          command: |
            python manage.py runserver
      - run:
          name: Run tests
          command: |
             ./manage.py test
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-
      - save_cache:
          paths:
            - python
          key: v1-dependencies-{{ checksum "requirements.txt" }}

workflows:
  main:
    jobs:
      - build-and-test
